package Chip.Gui;

import Chip.Component.Levels.*;
import Chip.Component.Status;
import Chip.Engine.Drawer;
import Chip.Engine.Engine;
import java.awt.event.KeyEvent;
import javax.swing.Timer;

/**
 *
 * @author TampanCrew Arts
 * @version 0.01 ALPHA
 */
public class Board extends javax.swing.JFrame{
    /**
     * engine yang akan menjalankan game ini
     */
    private Engine gameEngine;
    
    /**
     * array bertipe Level yang akan menampung data data level game ini
     */
    private Level[] levels;    
    
    /**
     * atribut ini adalah index untuk level yang sudah dilewati
     */
    private int levelPassed;    
    
    /**
     * atribut untuk menjalankan pengurangan waktu per detik
     */
    private Timer timer;    
    
    /**
     * atribut untuk menyimpan status permainan 
     */
    private Status status;

    /**
     * Creates new form Board
     */
    public Board() {
        initComponents();
        this.statField.setVisible(false);
        this.restartField.setVisible(false);
        this.gameFrame.setVisible(false);
        this.homePage.setVisible(true);
        this.hintField.setVisible(false);
        this.victoryField.setVisible(false);
        this.levelPassed=0;
        this.levels=new Level[Level.levelCount];
        this.levels[0]=new LevelZero();
        this.levels[1]=new LevelOne();
    }
    
    /**
     * method ini berfungsi untuk memasukan drawer kedalam internal frame
     * @param d drawer yang akan dimasukan
     */
    public void setGameFrame(Drawer d)
    {
        this.gameFrame.getContentPane().add(d);
    }
    
    /**
     * method ini berfungsi untuk memasukan hint level yang sedang dimainkan
     * @param level level yang akan dimunculkan hintnya
     */
    public void setHint(Level level)
    {
        this.hintLabel.setText(level.getHint());
    }
    
    /**
     * method untuk mengubah visibility dari gameFrame
     * @param tf kondisi tampilan gameFrame, true untuk memunculkan, false untuk menghilangkan
     */
    public void setGameFrameVisible(boolean tf)
    {
        this.gameFrame.setVisible(tf);
    }
    
    /**
     * method untuk mengubah visibility dari victoryField
     * @param tf kondisi tampilan gameFrame, true untuk memunculkan, false untuk menghilangkan
     */
    public void setVictoryFieldVisible(boolean tf)
    {
        winLabel.setText("Selamat!! Level telah dilewati^^");
        this.victoryField.setVisible(tf);
    }
            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statField = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        diamondCountLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        inventoryLabel = new javax.swing.JLabel();
        homePage = new javax.swing.JPanel();
        startButton = new javax.swing.JButton();
        restartField = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        restartButton = new javax.swing.JButton();
        gameFrame = new javax.swing.JInternalFrame();
        victoryField = new javax.swing.JPanel();
        winLabel = new javax.swing.JLabel();
        NextButton = new javax.swing.JButton();
        hintField = new javax.swing.JPanel();
        hintLabel = new javax.swing.JLabel();
        OKButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Time Left : ");

        timeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        timeLabel.setText("-");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Diamond Left :");

        diamondCountLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        diamondCountLabel.setText("-");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Inventory :");

        inventoryLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        inventoryLabel.setText("-");

        javax.swing.GroupLayout statFieldLayout = new javax.swing.GroupLayout(statField);
        statField.setLayout(statFieldLayout);
        statFieldLayout.setHorizontalGroup(
            statFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statFieldLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inventoryLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(statFieldLayout.createSequentialGroup()
                        .addGroup(statFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(statFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(timeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                            .addComponent(diamondCountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(statFieldLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        statFieldLayout.setVerticalGroup(
            statFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statFieldLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeLabel))
                .addGap(18, 18, 18)
                .addGroup(statFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diamondCountLabel))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inventoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(184, Short.MAX_VALUE))
        );

        homePage.setToolTipText("");

        startButton.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        startButton.setText("START MALING CHALLENGE");
        startButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout homePageLayout = new javax.swing.GroupLayout(homePage);
        homePage.setLayout(homePageLayout);
        homePageLayout.setHorizontalGroup(
            homePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(startButton, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                .addContainerGap())
        );
        homePageLayout.setVerticalGroup(
            homePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePageLayout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel5.setText("YOU LOSE!!");

        restartButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        restartButton.setText("RESTART");
        restartButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                restartButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout restartFieldLayout = new javax.swing.GroupLayout(restartField);
        restartField.setLayout(restartFieldLayout);
        restartFieldLayout.setHorizontalGroup(
            restartFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, restartFieldLayout.createSequentialGroup()
                .addContainerGap(174, Short.MAX_VALUE)
                .addGroup(restartFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(restartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(162, 162, 162))
        );
        restartFieldLayout.setVerticalGroup(
            restartFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(restartFieldLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(restartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        gameFrame.setPreferredSize(new java.awt.Dimension(610, 500));
        gameFrame.setVisible(true);
        gameFrame.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                gameFrameKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout gameFrameLayout = new javax.swing.GroupLayout(gameFrame.getContentPane());
        gameFrame.getContentPane().setLayout(gameFrameLayout);
        gameFrameLayout.setHorizontalGroup(
            gameFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
        );
        gameFrameLayout.setVerticalGroup(
            gameFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 485, Short.MAX_VALUE)
        );

        winLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        winLabel.setText("-");

        NextButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NextButton.setText("Next");
        NextButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NextButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout victoryFieldLayout = new javax.swing.GroupLayout(victoryField);
        victoryField.setLayout(victoryFieldLayout);
        victoryFieldLayout.setHorizontalGroup(
            victoryFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, victoryFieldLayout.createSequentialGroup()
                .addContainerGap(174, Short.MAX_VALUE)
                .addGroup(victoryFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(winLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(162, 162, 162))
        );
        victoryFieldLayout.setVerticalGroup(
            victoryFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(victoryFieldLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(winLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(NextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        hintLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hintLabel.setText("-");

        OKButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        OKButton.setText("OK");
        OKButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OKButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout hintFieldLayout = new javax.swing.GroupLayout(hintField);
        hintField.setLayout(hintFieldLayout);
        hintFieldLayout.setHorizontalGroup(
            hintFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hintFieldLayout.createSequentialGroup()
                .addContainerGap(194, Short.MAX_VALUE)
                .addGroup(hintFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OKButton, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hintLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(162, 162, 162))
        );
        hintFieldLayout.setVerticalGroup(
            hintFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hintFieldLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(hintLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(OKButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(168, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(homePage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(610, 610, 610)
                    .addComponent(statField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(restartField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(190, 190, 190)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(gameFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 200, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(hintField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(190, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(105, 105, 105)
                    .addComponent(victoryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(105, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(homePage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 47, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(statField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(25, 25, 25)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(restartField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(gameFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(hintField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(32, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(victoryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(30, Short.MAX_VALUE)))
        );

        try {
            gameFrame.setMaximum(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void restartButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restartButtonMouseClicked
        OKButtonMouseClicked(evt);
        this.restartField.setVisible(false);
    }//GEN-LAST:event_restartButtonMouseClicked

    private void startButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startButtonMouseClicked
        this.homePage.setVisible(false);
        this.hintField.setVisible(true);
        this.hintLabel.setText(levels[levelPassed].getHint());
    }//GEN-LAST:event_startButtonMouseClicked

    private void gameFrameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gameFrameKeyPressed
        int arrowKey = evt.getKeyCode();
        int direction;
        if (arrowKey == KeyEvent.VK_LEFT) {
            gameEngine.runMovingCondition(1);
        }
        else if (arrowKey == KeyEvent.VK_UP) {
            gameEngine.runMovingCondition(0);
        }
        else if (arrowKey == KeyEvent.VK_RIGHT) {
            gameEngine.runMovingCondition(3);
        }
        else if (arrowKey == KeyEvent.VK_DOWN) {
            gameEngine.runMovingCondition(2);
        }
    }//GEN-LAST:event_gameFrameKeyPressed

    private void OKButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OKButtonMouseClicked
        this.statField.setVisible(true);
        this.gameFrame.setVisible(true);
        this.hintField.setVisible(false);
        if(gameEngine==null){
            gameEngine= new Engine(levels[levelPassed], this);
        } else {
            gameEngine.updateNewEngine(levels[levelPassed]);
        }
        this.gameFrame.setFocusable(true);
    }//GEN-LAST:event_OKButtonMouseClicked

    private void NextButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NextButtonMouseClicked
        this.levelPassed++;
        if(levelPassed<levels.length)
        {
            this.victoryField.setVisible(false);
            this.gameFrame.setVisible(false);
            hintLabel.setText(levels[levelPassed].getHint());
            this.hintField.setVisible(true);
            if(gameEngine==null)
            {
                gameEngine=new Engine(levels[levelPassed],this);
            } else {
            gameEngine.updateNewEngine(levels[levelPassed]);
        }
        } else {
            hintLabel.setText("Selamat!! Game ini telah ditamatkan^^");
        }
        
    }//GEN-LAST:event_NextButtonMouseClicked

    /**
     * method ini berfungsi untuk mengantur tampilan saat game berakhir dengan kekalahan
     */
    public void gameOver()
    {
        this.gameFrame.setVisible(false);
        if(this.victoryField.isVisible()==false)
        {
            this.restartField.setVisible(true);
        }
    }
    
    /**
     * method ini akan menampilkan waktu yang tersisa 
     * @param timeLeft waktu yang tersisa
     */
    public void updateTime(int timeLeft)
    {
        this.timeLabel.setText(""+timeLeft);
    }
    
    /**
     * method ini akan menampilkan diamond yang tersisa 
     * @param diamonds diamonds yang tersisa
     */
    public void updateDiamondLeft(int diamonds)
    {
        this.diamondCountLabel.setText(diamonds+"");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Board().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NextButton;
    private javax.swing.JButton OKButton;
    private javax.swing.JLabel diamondCountLabel;
    private javax.swing.JInternalFrame gameFrame;
    private javax.swing.JPanel hintField;
    private javax.swing.JLabel hintLabel;
    private javax.swing.JPanel homePage;
    private javax.swing.JLabel inventoryLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton restartButton;
    private javax.swing.JPanel restartField;
    private javax.swing.JButton startButton;
    private javax.swing.JPanel statField;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JPanel victoryField;
    private javax.swing.JLabel winLabel;
    // End of variables declaration//GEN-END:variables

}
